import = [
    "~/.config/alacritty/alacritty-theme/themes/dracula.toml"
]

[shell]
    # program = "/opt/homebrew/bin/tmux"
    program = "/opt/homebrew/bin/bash"
    args = ["-l"]

[env]
    TERM = "xterm-256color"

[window]
    padding.x = 8
    padding.y = 4

    decorations = "Buttonless"

    opacity = 0.91
    blur = false

    # option_as_alt = "Both"
    
[font]
    normal.family = "AnonymicePro Nerd Font Mono"

    size = 15

[colors]
    transparent_background_colors = true
