# Use the color palette
palette = "dracula"

format = '''
[┌──](bold white)$username@$hostname $directory$git_branch$git_state$git_status$python$fill$cmd_duration [\[](bold)$time[\]](bold)
[└─](bold white)$character'''

[username]
format = "[$user]($style)"
style_root = "bold orange"
style_user = "bold orange"
show_always = true
disabled = false

[hostname]
format = "[$hostname]($style)"
style = "bold orange"
ssh_only = false
disabled = false

[directory]
# note: root git repo is no longer truncated when fish_style_pwd_dir_length is active
format = "[$path]($style)"
style = "purple"
truncation_length = 2
truncation_symbol = ".../"
disabled = false
repo_root_style = "underline purple"
fish_style_pwd_dir_length = 1

[character]
# another option (to copy) ❯
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'
vimcmd_symbol = '[\$](purple)'

[git_branch]
# note: when I'm in a git repository, a space automatically shows up at the end of the directory until the fish prompt is activated
disabled = false
symbol = ''
format = "[on](#ffffff) [$branch]($style)"
style = "cyan"

[git_status]
disabled = false
style = "pink"
modified = "*"

[python]
format = ' [(\($virtualenv\) )]($style)'
style = "green"
disabled = false

[cmd_duration]
format = " [$duration]($style)"
style = "yellow bold"
min_time = 0
show_milliseconds = false

[time]
format = "[$time]($style)"
style = "dimmed white"
use_12hr = true
disabled = false

[fill]
# symbol = "—"
symbol = " "
style = "0xffffff"

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
